name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [14.x]

    steps:

      - name: CD - Pull source code
        uses: appleboy/ssh-action@master
        with:
          host: 13.215.133.39
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: cd /home/ubuntu/server && git fetch origin main && git reset --hard origin/main && git pull
      - name: CD - Install dependencies
        uses: appleboy/ssh-action@master
        with:
          host: 13.215.133.39
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: cd /home/ubuntu/server && npm install
      - name: CD - Kill all ExpressJS process
        uses: appleboy/ssh-action@master
        with:
          host: 13.215.133.39
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: (fuser -n tcp -k 3000) || true
      - name: CD - Start ExpressJS Nodemon. Please wait 1 minute after this!
        uses: appleboy/ssh-action@master
        with:
          host: 13.215.133.39
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: cd /home/ubuntu/server && nodemon &
        timeout-minutes: 1
